### PR TITLE
Use dependency ranges

### PR DESCRIPTION
**Pull request by piranna**
It's not good to use fixed version on dependencies of a library, since it can cause conflicts with other ones.

### CODE REVIEW

**Comment by SamyPesse** [comment]
Well, I disagree with this, I prefer to keep our npm dependencies immutable. We can't "trust" the other packages (sometimes breaking changes are released as minor fixes. etc).

I want to be able to rollback to an old version of our packages and have the **exact** same behaviour as before.

**Comment by piranna** [comment]
Different point of view...

**Comment by SamyPesse** [comment]
@piranna Yes :) Let's agree to disagree.

What did you mean by "it can cause conflicts with other ones" ? npm/node works well with dpeendencies tree, it'll only cause larger `node_modules`.

**Comment by piranna** [comment]
> @piranna Yes :) Let's agree to disagree.

Lol :-P


> What did you mean by "it can cause conflicts with other ones" ? npm/node works well with dependencies tree, it'll only cause larger node_modules.

I've had problems in the past because the `node-canvas` version was really old and didn't worked with recent versions of Node.js, that's why I did my previous pull-request upgrading it. By allowing the usage of ranges, it would have used the latest semver compatible one, so this problem would have not arised.

It's better to get compatibility problems with old versions that can be fixed by upgrading them (and maybe deprecating old ones), that get compatibility problems with newer ones and to be forced to use old ones.

**Pull request closed without merging**
