### PR TITLE
Upgrade deps: resolve breaking compilation

### PR DESCRIPTION
**Pull request by piecioshka**
I've just resolve problems: #21 #17 and #12 and fix tests, which are broken too.

@piranna please merge this PR.

Additionally I've reformat code:
* add some spaces
* replace double quotes by single quotes

If that changes are not approve by you I can revert them, but I think that this project should be updated since 2016.

Regards!

### CODE REVIEW

**Comment by piecioshka** [comment]
ping @GitbookIO

**Comment by piecioshka** [comment]
ping @SamyPesse @spastorelli @jpreynat @taranvohra

**Comment by jpreynat** [comment]
@piecioshka Thanks for your contribution, but official GitBook plugins for the GitBook CLI have been deprecated a few years ago and are not maintained anymore.

If you are still using the GitBook CLI, you should be able to publish your own `gitbook-plugin-` and/or use it locally for your docs though 🙂

**Comment by piecioshka** [comment]
oh! I didn't know about it. Thanks @jpreynat 💪

**Pull request closed without merging**
